<a href="https://colab.research.google.com/github/Starlord02a/Manthan_RL/blob/main/Qlearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Define the environment
env = np.array([
    [-1, -1, -1, -1, 0, -1],
    [-1, -1, -1, 0, -1, 100],
    [-1, -1, -1, 0, -1, -1],
    [-1, 0, 0, -1, 0, -1],
    [0, -1, -1, 0, -1, 100],
    [-1, 0, -1, -1, 0, 100]
])

# Define the Q matrix
Q = np.zeros_like(env)

# Define the hyperparameters
alpha = 1
gamma = 0.8
num_episodes = 1000

# Run the Q-Learning algorithm
for episode in range(num_episodes):
    state = np.random.randint(0, env.shape[0])
    while state != 5:
        action = np.random.choice(np.where(env[state] != -1)[0])
        next_state = action
        reward = env[state, action]
        Q[state, action] = (1 - alpha) * Q[state, action] + alpha * (reward + gamma * np.max(Q[next_state]))
        state = next_state

# Print the learned Q matrix
print(Q)

[[  0   0   0   0  80   0]
 [  0   0   0  64   0 100]
 [  0   0   0  64   0   0]
 [  0  80  51   0  80   0]
 [ 64   0   0  64   0 100]
 [  0   0   0   0   0   0]]
